- name: 13. set hostname
  shell: hostnamectl set-hostname '{{ hostname }}'

- name: 12. create new hosts
  local_action: script create_hosts.sh
  run_once: true

- name: 11. update hosts
  local_action: script update_hosts.sh
  environment:
    ip: '{{ ansible_default_ipv4.address }}'
    hostname: '{{ hostname }}'

- name: 10. copy new hosts
  copy: src=hosts dest=/etc/hosts

- name: 09. copy limits.conf
  copy: src=limits.conf dest=/etc/security/limits.conf

- name: 08. copy 20-nproc.conf
  copy: src=20-nproc.conf dest=/etc/security/limits.d/20-nproc.conf

- name: 07. copy sysctl.conf
  copy: src=sysctl.conf dest=/etc/sysctl.conf

- name: 06. update kernel
  yum: name={{ item }} state=installed update_cache=yes
  with_items:
  - kernel-3.10.0-862.9.1.el7.x86_64
  - linux-firmware-20180220-62.2.git6d51311.el7_5.noarch

- name: 05. exec env script
  script: gpdb_env.sh 

- name: 04. add init.d file
  template: src={{ item }} dest=/etc/init.d/{{ item }} mode=755
  with_items:
  - blockdev-setra-sdb
  - disable-transparent-hugepages

- name: 03. add start file
  template: src={{ item }} dest=/etc/systemd/system/{{ item }} mode=755
  with_items:
  - blockdev-setra-sdb.service
  - disable-thp.service

- name: 02. sed start file
  service: name={{ item }} state=restarted enabled=yes
  with_items:
  - blockdev-setra-sdb.service
  - disable-thp.service

- name: 01. reboot host
  shell: sleep 5 && shutdown -r now
  async: 3
  poll: 0
  ignore_errors: true
